def student_id_card():
    name =input("enter your student name : ")
    father =input("enter your father name: ")
    mother =input("enter your mother name: ")
    city =input("enter your city name: ")
    roll =input("enter your roll number:")
    phone =input("enter your phone number: ")
    print("\n STUDENT ID CARD")
    print("name :", name )  
    print("Father name :",father)
    print("Mother name :",mother)
    print("city :",city)
    print("roll number:",roll)
    print("phone number:",phone)
student_id_card()
